controller_manager:
  ros__parameters:
    #6hz to match 150~ ms forced
    update_rate: 12

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base:
      type: diff_drive_controller/DiffDriveController


diff_drive_base:
  ros__parameters:
    # Wheel joint names (match URDF + ros2_control)
    left_wheel_names:  ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]

    # Geometry (MUST match your URDF)
    wheel_separation: 0.1524         # meters was 0.28
    wheel_radius:     0.03175         # meters was 0.05

    # Frames & topics
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_wheel_data: true
    open_loop: true
    position_feedback: false

    # Command interface
    use_stamped_vel: true          # publishes /diff_drive_base/cmd_vel_unstamped
    cmd_vel_timeout: 0.5
    velocity_rolling_window_size: 10

    # Limits (adjust as needed)
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.6
        has_acceleration_limits: true
        max_acceleration: 1.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 3.0
