/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as DevicesOldRouteImport } from './routes/devices-old'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ControlPanelRouteImport } from './routes/control-panel'
import { Route as IndexRouteImport } from './routes/index'

const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesOldRoute = DevicesOldRouteImport.update({
  id: '/devices-old',
  path: '/devices-old',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelRoute = ControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/devices-old': typeof DevicesOldRoute
  '/lesson': typeof LessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/devices-old': typeof DevicesOldRoute
  '/lesson': typeof LessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/devices-old': typeof DevicesOldRoute
  '/lesson': typeof LessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control-panel' | '/devices' | '/devices-old' | '/lesson'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control-panel' | '/devices' | '/devices-old' | '/lesson'
  id:
    | '__root__'
    | '/'
    | '/control-panel'
    | '/devices'
    | '/devices-old'
    | '/lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlPanelRoute: typeof ControlPanelRoute
  DevicesRoute: typeof DevicesRoute
  DevicesOldRoute: typeof DevicesOldRoute
  LessonRoute: typeof LessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices-old': {
      id: '/devices-old'
      path: '/devices-old'
      fullPath: '/devices-old'
      preLoaderRoute: typeof DevicesOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel': {
      id: '/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof ControlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlPanelRoute: ControlPanelRoute,
  DevicesRoute: DevicesRoute,
  DevicesOldRoute: DevicesOldRoute,
  LessonRoute: LessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
