/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Setup2RouteImport } from './routes/setup2'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as ControlPanelRouteImport } from './routes/control-panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as LessonsIntroRouteImport } from './routes/lessons/intro'

const Setup2Route = Setup2RouteImport.update({
  id: '/setup2',
  path: '/setup2',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelRoute = ControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIntroRoute = LessonsIntroRouteImport.update({
  id: '/lessons/intro',
  path: '/lessons/intro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/setup': typeof SetupRoute
  '/setup2': typeof Setup2Route
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/setup': typeof SetupRoute
  '/setup2': typeof Setup2Route
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons': typeof LessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-panel': typeof ControlPanelRoute
  '/devices': typeof DevicesRoute
  '/setup': typeof SetupRoute
  '/setup2': typeof Setup2Route
  '/lessons/intro': typeof LessonsIntroRoute
  '/lessons/': typeof LessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control-panel'
    | '/devices'
    | '/setup'
    | '/setup2'
    | '/lessons/intro'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control-panel'
    | '/devices'
    | '/setup'
    | '/setup2'
    | '/lessons/intro'
    | '/lessons'
  id:
    | '__root__'
    | '/'
    | '/control-panel'
    | '/devices'
    | '/setup'
    | '/setup2'
    | '/lessons/intro'
    | '/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlPanelRoute: typeof ControlPanelRoute
  DevicesRoute: typeof DevicesRoute
  SetupRoute: typeof SetupRoute
  Setup2Route: typeof Setup2Route
  LessonsIntroRoute: typeof LessonsIntroRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup2': {
      id: '/setup2'
      path: '/setup2'
      fullPath: '/setup2'
      preLoaderRoute: typeof Setup2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel': {
      id: '/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof ControlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/intro': {
      id: '/lessons/intro'
      path: '/lessons/intro'
      fullPath: '/lessons/intro'
      preLoaderRoute: typeof LessonsIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlPanelRoute: ControlPanelRoute,
  DevicesRoute: DevicesRoute,
  SetupRoute: SetupRoute,
  Setup2Route: Setup2Route,
  LessonsIntroRoute: LessonsIntroRoute,
  LessonsIndexRoute: LessonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
